import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

// @ is an alias that Next.js provides for the src directory, so it points to the src folder in your Next.js project.
// Using "../css/variables.css" would work if you are outside the src directory, but it is not recommended because it is more verbose and relies on relative paths
import "@/css/variables.css"; // Import your variables
import "@/css/globals.css"; // Import your global styles
import "@/css/customSwiper.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
